echo "Prediction Size = 1" > "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 1 1 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-1-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 2" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 2 1 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-2-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 3" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 3 1 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-3-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 4" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 4 1 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-4-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 5" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 5 1 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-5-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 10" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 10 1 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-10-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 20" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 20 1 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-20-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 50" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 50 1 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-50-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 100" >> "Results\FinalResults.txt"
echo "Prediction Size = 1" > "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 1 2 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-1-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 2" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 2 2 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-2-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 3" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 3 2 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-3-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 4" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 4 2 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-4-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 5" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 5 2 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-5-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 10" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 10 2 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-10-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 20" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 20 2 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-20-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 50" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 50 2 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-50-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 100" >> "Results\FinalResults.txt"
echo "Prediction Size = 1" > "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 1 5 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-1-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 2" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 2 5 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-2-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 3" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 3 5 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-3-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 4" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 4 5 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-4-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 5" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 5 5 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-5-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 10" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 10 5 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-10-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 20" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 20 5 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-20-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 50" >> "Results\FinalResults.txt"
./wum PagePredictor log-university-testing topology-university.txt Predictor.txt 50 5 to-all-patterns.txt ssra-all-patterns.txt csra-all-patterns.txt IP-all-patterns.txt no-all-patterns.txt ceng.metu.edu.tr >> "Results\FinalResults.txt"
cat "Results\PredictionResults-50-1.txt" >> "Results\FinalResults.txt"
echo "Prediction Size = 100" >> "Results\FinalResults.txt"